import { Link } from 'react-router-dom';

export default function Story() {
  return (
    <>
      <style>{`
        .story-title{font-size:clamp(26px,4vw,34px);font-weight:800;letter-spacing:3px;text-transform:uppercase;margin-bottom:14px;}
        .story-sep{width:60px;height:2px;background:var(--copper);margin-bottom:40px;border-radius:2px;}
        .story-body p{font-size:16px;line-height:1.85;color:var(--ink-2);margin-bottom:22px;}
        .story-back{display:inline-block;margin-bottom:24px;font-size:13px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:var(--copper);}
        .story-back:hover{text-decoration:underline;}
        .story-bottom{margin-top:48px;padding-top:24px;border-top:1px solid var(--line);}
      `}</style>
      <main className="page narrow">
        <Link to="/about" className="story-back">← Back to about</Link>
        <h1 className="story-title">My life story</h1>
        <div className="story-sep"></div>

        <div className="story-body">
          <p>My name is Michael and I&rsquo;m 41 years old. I&apos;ve been addicted to, primarily pornography, since I was around 10 years old. Porn was my first real addiction, followed by computer games, nicotine, alcohol, drugs (amphetamine and benzos primarily) in that order. Porn was always the main pillar of my addictions, and was also the hardest one to quit of them all, by far.</p>

          <p>I had a very chaotic upbringing, my mother was an alcoholic and I could not really invite friends over to my place. Computer games and porn was my escape and I spent more and more time in fantasy world than in the real world. By the time I was done with the primary school (up to age 14 I believe) and would enter high school, I had no interest or drive for that in the slightest and ended up skipping that alltogether.</p>

          <p>I got myself in to an online relationship with a woman, which started when I was 16 or 17, and eventually we moved in together by the time I was 21. At this point I would be doing various things like working at Mcdonalds, working construction, trying to get my high school exam sorted via an &ldquo;adult education&rdquo; program, but nothing really stuck. The addiction was with me even throughout having a relationship. When I was 22, my mother passed away due to her alcoholism, her liver simply gave up on her. I still remember her yellow eyewhites and bloated body/face. It was incredibly painful emotionally for me and I used what I knew worked to &ldquo;feel good&rdquo; temporarily to keep escaping the pain, alcohol, games and porn (drugs wasn&apos;t present until I hit my 30s).</p>

          <p>Fast forward some to when I was 27, my girlfriend (we lived together but were not married) got uterus cancer. This was incredibly taxing on her and on the relationship of course, and after almost a year of treatment, she managed to beat it at first. Something that we celebrated immensely.</p>

          <p>A few months later, she had a re-examination, and it was found that there was some of it left that had started to spread a lot. At this point it was clear she had no strenght to fight it again and she had mentally given up. She was eventually placed in a hospice where I sat with her until her body gave up and she passed away. This left me with absolutely zero will, drive or purpose in life anymore and to say that I was depressed would be an enormous understatement. I was just a walking corpse.</p>

          <p>I moved back in with my adoptive father (my biological father passed away when I was very little, I never remembered him or really met him, so my adoptive father is my real father in that sense) and I spent several years in an internal misery, pain, some pretend/fantasy online relationships here and there, alcohol, weed started to become more of a regular thing as well.</p>

          <p>Fast forward a bit here too, after living in fantasy land for a few more years, I was literally decaying to my death. I was getting fatty liver, my dental health was a catastrophy (I had periodontitis even at that age with severe bone loss) and I believe at my worst, I weighed around 52-53kg, which is really thin for a male even if I&apos;m not particularly tall at 176cm. The pleasure-spikes of pornography even hijacked my apetite many times, even if it wasn&apos;t pornography alone, it indirectly assisted in it through the severe depression I was in at the time.</p>

          <p>By some type of coincidence (I can&apos;t even remember details here, life was so blurry and I was so self-medicated as well as &ldquo;professionally&rdquo; medicated via SSRI&apos;s) I find NoFap. Up until this point, I knew I was addicted to porn, but I didn&apos;t really make the connection of the immense negative and destructive impact this particular addiction had on my life, on my well being, on my drive, motivation, self respect, self confidence and self love. I thought that depression was just &ldquo;something I&apos;ve always had&rdquo; and that my traumatic life experiences just worsened it, the world was grey because of my unfortunate &ldquo;imbalance&rdquo; of hormones or molecules or whatever it was in my brain, and that the SSRI&apos;s, porn and alcohol and all the other stuff sort of &ldquo;balanced&rdquo; me out and that I needed that cocktail to feel good. I do not think there is an addiction that creates so much inner shame and anxiety as porn addiction does. All addictions contain secrecy, but there is something extreme in the amount of inner shame you build up when you&apos;re watching immense amount of porn.</p>

          <p>With NoFap I saw that there was a large amount of people reporting immense quality of life improvement when they stopped watching porn. At this time I was living on wellfare and going on some &ldquo;long time unemployed&rdquo;-program that my municipary held for people who had been unemployed for years. I was still the timid, anxiety ridden porn addict when I joined that program and went there regularly. I went there a few hours a day as an activity, refined my CV, etc. At the same time I started experimenting with this &ldquo;NoFap&rdquo; thing I had found and I slowly started regain some drive, some motivation, some life. I started helping out there at the program, a lot of refugees had no computer knowledge at all and I would help them because I had basically spent the majority of my life in front of a computer. So I started spending my time there helping the existing job coaches.</p>

          <p>I got an offer to work there as a &ldquo;trainee&rdquo;/intern, which I started doing, and the upward spiral began. I was working on myself so incredibly hard, and it showed, the co-workers did not recognize me. One co-worker <em>literally</em> did not recognize me and actually introduced herself to me after a meeting and asked if I had just started working there because she hadn&apos;t seen me before, when I had already been there for a few months, that is how invisible I was during my porn addict state, and the immense energy-level difference between an active addict, and a sober addict. I am still mind blown thinking back on that, I thought she was joking at first but she was serious in the introduction. My boss there said I was like a completely different person. This shift happened fairly quick, but not overnight. I was replacing my porn habits with working out, reading books, meditating daily, cold showers. I stopped nicotine (I had been doing &ldquo;snus&rdquo; since I was around 13 years old), I stopped alcohol, I stopped energy drinks, I stopped all types of medication. It was all possible because I attacked the <em>root</em> addiction first in my case, which is pornography. The rest fell like dominos afterwards.</p>

          <p>After a few months as an intern, I received a real job offer there as a coach. That is a job that normally requires a university degree of some sort, and I had barely finished high school. I worked there for a couple of years, and the &ldquo;extremes&rdquo; started to mellow down, I worked out, but didn&apos;t challenge myself as regularly, the cold shower honeymoon stopped and I got used to the cold water and didn&apos;t feel as superman anymore after each cold shower and so on. During my upward spiral, my friendship circle changed too. It&apos;s very hard to maintain the same type of friendship circle that you had when you were at your lowest points in your life, due to hierarchical and dynamic reasons I believe. It is very hard for other people (old friends) to &ldquo;accept&rdquo; the new you, when their memory has your old, much weaker baseline hard coded in to them, if they refuse to accept and adjust accordingly to your new baseline, and you refuse to get pulled down and accept your old, now dead baseline, then you have no choice but to detach from them and move on. It isn&apos;t something dramatic, it&apos;s just how life is. Life is change.</p>

          <p>I&apos;m now in my early-mid 30s and I get a new job, this time in IT, a very small company, only me and a man who has been working on this software by himself (plus a handful of Russian developers he had hired on distance, this was before the war started). We get along incredibly well, I become the companys&apos; face and start dealing with support issues, learning this incredibly complex automation software and providing support on a daily basis, my role expands and I start to hold presentations as well to the IT departments of potential customers (no private customers, all companies), which was nerv wrecking since I doubted my own competence in the face of senior IT-people who has been working with IT for 20+ years for example, and to be able to answer their questions and not make a fool out of myself. I started taking benzos/clonazepam daily, at this point it was pretty controlled, it just kept my nerves in check, I didn&apos;t abuse them, same amount every day for a few years.</p>

          <p>Covid hits, working from home becomes a real thing. I started drinking alcohol on weekends more frequently, the working out was just a routine, never challenged myself there or changed the routine up. Meditation became more infrequent.</p>

          <p>Now I make the biggest mistake ever, I open the floodgates by starting to use porn again. I rationalized it with &ldquo;well, I&apos;ve slayed these demons before, I know I have the willpower and discipline to do it again at will when it becomes a problem, right?&rdquo; I treated it as tap water that I could control the pressure of/turn it off whenever I wanted to. Unfortunately, that&apos;s not how it works with porn addiction, or with any addiction for that matter. It is so insidious in how the problems start sneaking up on you and you rationalize them over and over. It&apos;s like a window that gets dirtier and dirtier in such tiny increments that you don&apos;t even notice the fog and dirt overnight, you get used to it. It&apos;s not like someone throws a large amount of dirt and shit on a clean window that you immediately notice and clean up, it&apos;s more like someone puts a finger print on it, then the next day another fingerprint and so on.</p>

          <p>Porn becomes more and more of a regular thing, I start becoming more tired, brain foggy. Solution to that? Well I have an ADD-diagnose (I don&apos;t have ADD, but I have the diagnose. I know I don&apos;t have ADD because the symtoms of ADD only appears when I don&apos;t take care of my psychological health), so I got back on Vyvanse, something I&apos;ve been on once for a short period before. It&apos;s like amphetamine. Energy fixed. Vyvanse, benzos on a daily basis. Tolerance increases. I think I do well at work, my personality changes, I start to laser-focus on tiny details of things that don&apos;t really matter and so on. I do a lot, but get nothing done, yet I think I&apos;m killing it. Bigger doses. Doctor won&apos;t prescribe more, fine, I order amphetamines (at this point, my prefrontal cortex is fried, there is literally no hesitation in taking the step to ordering amphetamines from some shady criminal in the dark web at this stage). Porn is a steady and consistent factor at this point too. That part of slaying the demons I was rationalizing it with in the beginning? Yeah, that can wait a little longer, I have much more important things to do and take care of, porn isn&apos;t the issue, I&apos;m super busy at work, I have so many big ideas, working out can wait a bit too, I don&apos;t have time for that (that&apos;s the voice of my internal monologue at that point basically).</p>

          <p>I start becoming less interest in work and more interested in severe porn sessions, porn is still providing me the largest pleasure-spikes by far, combining porn and amphetamines, there is nothing in the real world that comes close to being able to compete with the dopamine spikes there, and when your prefrontal cortex and your brain is so severely hijacked, dopamine-pleasure spikes is all that matters to you, at the cost of everything else, relationships, friends, work, family, life.</p>

          <p>Long story short, I lose my job. I lose my appartment due to eviction from debt and through some incredible luck I manage to get a student housing/appartment in another city, at 17sq2, where I still live as of writing this.</p>

          <p>Fast-forwarding a bit, I completely stopped using pornography, and in doing that, I was able to kick amphetamines and benzodiazepines as well as abstaining from any alcohol or other bad habits. Again, porn is the foundation of all my addictions and has to be under control for any other bad habit to be kicked. This might not be true for everyone, but I know that it is true in my case because I have tried many times to &ldquo;keep&rdquo; porn (obviously my favorite addiction of all, the one addiction i both love and hate the most) and get rid of everything else, only to end up in the same place eventually, no progress at all. I currently live in complete celibacy, redirecting my sexual drive and energy towards healing myself, my life and building my mission, something that has worked incredibly well so far. My brain is no longer hijacked by sex and my focus and energy can go towards myself and my purpose. I don&apos;t intend on being celibate from real, healthy sex and intimacy all my life (self-sex, is something that I&apos;ll very likely never have again though), but I&apos;ve seen it as a necessity for me for this long period now.</p>

          <p>There are also some spiritual reasons to my celibacy choice that I won&apos;t go in to detail of here.</p>

          <p>I&apos;ve started running and is attempting my first marathon this year. I&apos;m dancing zumba and aerobics dance weekly, I&apos;m doing group yoga, I&apos;m making new friends, talking to people, learning new skills, taking toastmaster classes, learning a new job, reading daily, meditating and I&apos;m more at peace internally and happier on a day to day basis than I have ever been in my life I think. This is despite that I have nothing materialistic to show in my 41 year old life. I&apos;m in debt still, I&apos;m in a 17sq2 apartment, no car etc. Instead, I have an inner drive, and a life purpose and my pornography addiction under control. My life purpose is to spread awareness of the harms of something that even today is seen as something &ldquo;that is just casual fun&rdquo; by many people, using pornography. I am absolutely convinced of that pornography addiction is one of the most lonely and most insidious addiction there is. My life purpose is to become a man that I wish existed when I was 12-13 years old and internet pornography was just becoming reality, along with the addiction to it.</p>

          <p>I am currently under learning/an intern for Erik Sundby, who has been working with sex and porn addicts for over 20 years. He is the CEO of &ldquo;DBK Sverige&rdquo; which is the oldest clinic for treating sex addiction in Sweden, via therapy. I could not possibly have found a better mentor to learn from, nor a better work-place to get experience from that correlates with my life purpose. I have always been terrified, like scared to death, of public speaking, but that fear falls short in contrast to my fire, passion and drive towards my life mission of wanting to educate and steer the younger generation away from pornography. This is something that will require me to speak in public, to eventually visit schools, talk in classes, be vulnerable, tell my life story and so on. That is why I am taking Toastmaster classes now. That is also why I initially started taking Zumba classes, to train my brain to give absolutely zero fucks, walking in to that class the first time as the only male with 20 women staring at you and judging you is a good practice in the art of not giving a fuck. Now, several months later, I love dancing and I feel at home and very comfortable in those dance groups. I would also like to add that I've probably never felt this good and stable internally in my life before, there is no mania, no hint of depression, just a general state of well being on a day to day basis and a strong faith and belief in myself and my life purpose. To be able to feel like this without any type of drug or dopamine abuse is something I did not know was possible. I hope by reading that, that you (if you are struggling with addiction) feel inspired and know that you too, can certainly heal and feel incredible as well, without acting out on porn or drugs. If I can heal, after having absolutely wrecked myself with drugs, porn, SSRIs and other various medications, then you most definitely can.</p>

          <p>Obviously, not all porn addicts are timid introverts like I was. A large enough amount of porn addicts are though. Some can watch porn and be outgoing extroverts with no visible shame, no problems at all, I believe that it is mostly those who are in the early stages of the addiction that hasn&apos;t built up this immense, compounding, thick layer of shame internally yet, or they started watching pornography later on in life. I believe that it has much more of a severe effect on someone who start watching porn in the earlier ages of life, such as when I started. And this is the reality of today, boys are being exposed to porn and start seeing it first times when they are around 9 years old today, which is insane.</p>

          <p>Throughout my worst years, I&apos;ve also been frequently in contact with psychiatric health care, which did absolutely nothing for me except making it worse, basically numbing me, not assisting in the slightest as all they did was throw SSRI after SSRI on me and I probably went through 7-8 different SSRI&apos;s. I frequented several psychologists too (not private ones), none of them seemed to draw any connection to my depression and the way I was escaping my emotions via spending time at the computer, nor did anyone ask about my use of pornography, likely because either it&apos;s not fully seen as a &ldquo;problem&rdquo; that can lead to depression or addiction in the psychiatric care yet, or because it&apos;s just too much of a taboo thing to ask patients. Regardless of which, I&apos;m also not sure I would of been honest even if they asked because it&apos;s so incredibly shameful and anxiety-ridden when you&apos;re deep in that addiction yourself. The biggest problem is that I would not have wanted to talk about it with a psychiatrist who would not have had experience with porn addiction himself, and I believe many porn addicts feel the same way there.</p>
		  


          <p>That is why I believe in myself being open, vulnerable in my story and my addiction, I can help others. I am particularly passionate about helping the younger generation, those who are still in school, to talk to them about pornography addiction and the potential severity and consequences of it. There is nothing free or harmless about pornography, it has an immense cost and trade-off. There are likely many boys who are just as clueless as I was on the harms of pornography when I was their age. My life purpose is to become an adult for them, that I wish existed for me, when I was young.</p>

          <p>I want to end this long journey-post with two sentences that I regularly remind the people I mentor and help, things that I live by and that, through living by it, has helped me immensely in my self esteem, building integrity and my recovering.
           "Live your life as if everyone you love, both alive and dead, are watching you every single day and night" 
          As well as "A creep in the dark will always be a creep in the light". These are two things I live by, because I sincerely belive in them both. And by living after them, I am also becoming a person full of integrity and full of self esteem, which spills out positively in every area of my life.</p>

          <p>Michael</p>
        </div>

        <div className="story-bottom">
          <Link to="/about" className="story-back">← Back to about</Link>
        </div>
      </main>
    </>
  );
}
